baseURL = "https://tylzars.github.io/"
languageCode = "en-us"
title = "Tyler's Blog"
theme="archie"
copyright = "© Athul"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# General Parameters for site
[params]
	mode="toggle"
	useCDN=true
	subtitle = "A place for write-ups and other codebased information!"

# These come from: https://feathericons.com/?query=web
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/tylzars"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/tylzars"

[[params.social]]
name = "Personal Site"
icon = "layout"
url = "https://zars.me/home"

# Website top menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
